networks:
  metrics:

volumes:
  grafana-storage:
  prometheus:

services:
  metrics:
    container_name: metrics
    build: .
    networks:
      - metrics
    ports:
      - "80:80"
    volumes:
      - ".:/metrics"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - metrics
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prometheus:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    networks:
      - metrics
    ports:
      - "3000:3000"
    volumes:
      - ./configs/grafana:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
