global:
  scrape_interval: 5s

scrape_configs:
- job_name: prometheus
  static_configs:
    - targets:
        - metrics
  relabel_configs:
    - source_labels: [ '__address__' ]
      target_label: instance